wheel1_effort_controller:
   type: effort_controllers/JointEffortController
   joint: wheel1_joint
   pid: {p: 100.0, i: 0.01, d: 10.0}

wheel2_effort_controller:
   type: effort_controllers/JointEffortController
   joint: wheel2_joint
   pid: {p: 100.0, i: 0.01, d: 10.0}

wheel3_effort_controller:
   type: effort_controllers/JointEffortController
   joint: wheel3_joint
   pid: {p: 100.0, i: 0.01, d: 10.0}
